version: '3.8'

services:
  mysql-1:
    image: mysql:8.0
    container_name: mysql-1
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ehkpo88&$12
      MYSQL_DATABASE: accounting_db
    ports:
      - "3306:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    image: kelvin_accounting_api:latest
    container_name: api-1
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql-1:3306/accounting_db
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ehkpo88&$12
    depends_on:
      mysql-1:
        condition: service_healthy
